export type CurrencyEntry = { code: string; symbol: string; name: string };

export const CURRENCY_OPTIONS: CurrencyEntry[] = [
  { code: "INR",  symbol: "₹",     name: "Indian Rupee" },
  { code: "USD",  symbol: "$",     name: "US Dollar" },
  { code: "EUR",  symbol: "€",     name: "Euro" },
  { code: "GBP",  symbol: "£",     name: "British Pound" },
  { code: "AED",  symbol: "د.إ",  name: "UAE Dirham" },
  { code: "SAR",  symbol: "﷼",    name: "Saudi Riyal" },
  { code: "QAR",  symbol: "ر.ق",  name: "Qatari Riyal" },
  { code: "KWD",  symbol: "د.ك",  name: "Kuwaiti Dinar" },
  { code: "BHD",  symbol: "BD",    name: "Bahraini Dinar" },
  { code: "OMR",  symbol: "ر.ع.", name: "Omani Rial" },
  { code: "PKR",  symbol: "Rs",    name: "Pakistani Rupee" },
  { code: "BDT",  symbol: "৳",    name: "Bangladeshi Taka" },
  { code: "LKR",  symbol: "Rs",    name: "Sri Lankan Rupee" },
  { code: "NPR",  symbol: "Rs",    name: "Nepalese Rupee" },
  { code: "SGD",  symbol: "S$",    name: "Singapore Dollar" },
  { code: "MYR",  symbol: "RM",    name: "Malaysian Ringgit" },
  { code: "PHP",  symbol: "₱",    name: "Philippine Peso" },
  { code: "IDR",  symbol: "Rp",    name: "Indonesian Rupiah" },
  { code: "THB",  symbol: "฿",    name: "Thai Baht" },
  { code: "VND",  symbol: "₫",    name: "Vietnamese Dong" },
  { code: "JPY",  symbol: "¥",    name: "Japanese Yen" },
  { code: "CNY",  symbol: "¥",    name: "Chinese Yuan" },
  { code: "KRW",  symbol: "₩",    name: "South Korean Won" },
  { code: "HKD",  symbol: "HK$",  name: "Hong Kong Dollar" },
  { code: "TWD",  symbol: "NT$",  name: "New Taiwan Dollar" },
  { code: "AUD",  symbol: "A$",   name: "Australian Dollar" },
  { code: "CAD",  symbol: "C$",   name: "Canadian Dollar" },
  { code: "NZD",  symbol: "NZ$",  name: "New Zealand Dollar" },
  { code: "CHF",  symbol: "CHF",  name: "Swiss Franc" },
  { code: "ZAR",  symbol: "R",    name: "South African Rand" },
  { code: "NGN",  symbol: "₦",    name: "Nigerian Naira" },
  { code: "GHS",  symbol: "₵",    name: "Ghanaian Cedi" },
  { code: "KES",  symbol: "KSh",  name: "Kenyan Shilling" },
  { code: "EGP",  symbol: "E£",   name: "Egyptian Pound" },
  { code: "MXN",  symbol: "MX$",  name: "Mexican Peso" },
  { code: "BRL",  symbol: "R$",   name: "Brazilian Real" },
  { code: "RUB",  symbol: "₽",    name: "Russian Ruble" },
  { code: "TRY",  symbol: "₺",    name: "Turkish Lira" },
  { code: "PLN",  symbol: "zł",   name: "Polish Złoty" },
  { code: "SEK",  symbol: "kr",   name: "Swedish Krona" },
];
